// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type RaffleEntry = {
  id: bigint,
  wallet: string,
  username: string,
  email: string,
  tokenBalance: string,
  usdValue: number,
  timestamp: __Timestamp,
  entryHash: string,
};
/**
 * An object for generated helper functions.
 */
export const RaffleEntry = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "wallet", algebraicType: __AlgebraicTypeValue.String},
        { name: "username", algebraicType: __AlgebraicTypeValue.String},
        { name: "email", algebraicType: __AlgebraicTypeValue.String},
        { name: "tokenBalance", algebraicType: __AlgebraicTypeValue.String},
        { name: "usdValue", algebraicType: __AlgebraicTypeValue.F64},
        { name: "timestamp", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "entryHash", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: RaffleEntry): void {
    __AlgebraicTypeValue.serializeValue(writer, RaffleEntry.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): RaffleEntry {
    return __AlgebraicTypeValue.deserializeValue(reader, RaffleEntry.getTypeScriptAlgebraicType());
  },

}

export default RaffleEntry;


