// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type SaveJournalEntry = {
  wallet: string,
  cardId: number,
  date: __Timestamp,
  prompt1: string,
  prompt2: string,
  prompt3: string,
  wordCount: number,
  completed: boolean,
};
/**
 * An object for generated helper functions.
 */
export const SaveJournalEntry = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "wallet", algebraicType: __AlgebraicTypeValue.String},
        { name: "cardId", algebraicType: __AlgebraicTypeValue.U32},
        { name: "date", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "prompt1", algebraicType: __AlgebraicTypeValue.String},
        { name: "prompt2", algebraicType: __AlgebraicTypeValue.String},
        { name: "prompt3", algebraicType: __AlgebraicTypeValue.String},
        { name: "wordCount", algebraicType: __AlgebraicTypeValue.U32},
        { name: "completed", algebraicType: __AlgebraicTypeValue.Bool},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: SaveJournalEntry): void {
    __AlgebraicTypeValue.serializeValue(writer, SaveJournalEntry.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): SaveJournalEntry {
    return __AlgebraicTypeValue.deserializeValue(reader, SaveJournalEntry.getTypeScriptAlgebraicType());
  },

}

export default SaveJournalEntry;

