
create table cards_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  card_id bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
