// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.5.0 (commit ).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { AwardXp } from "./award_xp_reducer";
export { AwardXp };
import { CaptureEmail } from "./capture_email_reducer";
export { CaptureEmail };
import { CheckDailyLimit } from "./check_daily_limit_reducer";
export { CheckDailyLimit };
import { CompleteReferral } from "./complete_referral_reducer";
export { CompleteReferral };
import { CreateReferral } from "./create_referral_reducer";
export { CreateReferral };
import { CreateUser } from "./create_user_reducer";
export { CreateUser };
import { EnterRaffle } from "./enter_raffle_reducer";
export { EnterRaffle };
import { GetRaffleCount } from "./get_raffle_count_reducer";
export { GetRaffleCount };
import { GetRaffleEntries } from "./get_raffle_entries_reducer";
export { GetRaffleEntries };
import { RecordFreePull } from "./record_free_pull_reducer";
export { RecordFreePull };
import { RecordPull } from "./record_pull_reducer";
export { RecordPull };
import { SaveJournalEntry } from "./save_journal_entry_reducer";
export { SaveJournalEntry };
import { SelectWeightedWinner } from "./select_weighted_winner_reducer";
export { SelectWeightedWinner };
import { ToggleFavorite } from "./toggle_favorite_reducer";
export { ToggleFavorite };
import { UnlockAchievement } from "./unlock_achievement_reducer";
export { UnlockAchievement };
import { UpdateUsername } from "./update_username_reducer";
export { UpdateUsername };

// Import and reexport all table handle types
import { AchievementTableHandle } from "./achievement_table";
export { AchievementTableHandle };
import { ActivePackTableHandle } from "./active_pack_table";
export { ActivePackTableHandle };
import { CardPullTableHandle } from "./card_pull_table";
export { CardPullTableHandle };
import { EmailCaptureTableHandle } from "./email_capture_table";
export { EmailCaptureTableHandle };
import { FavoriteTableHandle } from "./favorite_table";
export { FavoriteTableHandle };
import { FreePullTableHandle } from "./free_pull_table";
export { FreePullTableHandle };
import { JournalEntryTableHandle } from "./journal_entry_table";
export { JournalEntryTableHandle };
import { JournalStreakTableHandle } from "./journal_streak_table";
export { JournalStreakTableHandle };
import { PackClaimTableHandle } from "./pack_claim_table";
export { PackClaimTableHandle };
import { PackUsageStatTableHandle } from "./pack_usage_stat_table";
export { PackUsageStatTableHandle };
import { RaffleEntryTableHandle } from "./raffle_entry_table";
export { RaffleEntryTableHandle };
import { ReferralTableHandle } from "./referral_table";
export { ReferralTableHandle };
import { TimedPullTableHandle } from "./timed_pull_table";
export { TimedPullTableHandle };
import { UserTableHandle } from "./user_table";
export { UserTableHandle };
import { VibeBalanceTableHandle } from "./vibe_balance_table";
export { VibeBalanceTableHandle };
import { XpTransactionTableHandle } from "./xp_transaction_table";
export { XpTransactionTableHandle };

// Import and reexport all types
import { Achievement } from "./achievement_type";
export { Achievement };
import { ActionType } from "./action_type_type";
export { ActionType };
import { ActivePack } from "./active_pack_type";
export { ActivePack };
import { CardPull } from "./card_pull_type";
export { CardPull };
import { EmailCapture } from "./email_capture_type";
export { EmailCapture };
import { Favorite } from "./favorite_type";
export { Favorite };
import { FreePull } from "./free_pull_type";
export { FreePull };
import { JournalEntry } from "./journal_entry_type";
export { JournalEntry };
import { JournalStreak } from "./journal_streak_type";
export { JournalStreak };
import { PackClaim } from "./pack_claim_type";
export { PackClaim };
import { PackUsageStat } from "./pack_usage_stat_type";
export { PackUsageStat };
import { RaffleEntry } from "./raffle_entry_type";
export { RaffleEntry };
import { Referral } from "./referral_type";
export { Referral };
import { TimedPull } from "./timed_pull_type";
export { TimedPull };
import { User } from "./user_type";
export { User };
import { VibeBalance } from "./vibe_balance_type";
export { VibeBalance };
import { XpTransaction } from "./xp_transaction_type";
export { XpTransaction };

const REMOTE_MODULE = {
  tables: {
    achievement: {
      tableName: "achievement",
      rowType: Achievement.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Achievement.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    active_pack: {
      tableName: "active_pack",
      rowType: ActivePack.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (ActivePack.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    card_pull: {
      tableName: "card_pull",
      rowType: CardPull.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (CardPull.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    email_capture: {
      tableName: "email_capture",
      rowType: EmailCapture.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (EmailCapture.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    favorite: {
      tableName: "favorite",
      rowType: Favorite.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Favorite.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    free_pull: {
      tableName: "free_pull",
      rowType: FreePull.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (FreePull.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    journal_entry: {
      tableName: "journal_entry",
      rowType: JournalEntry.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (JournalEntry.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    journal_streak: {
      tableName: "journal_streak",
      rowType: JournalStreak.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (JournalStreak.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    pack_claim: {
      tableName: "pack_claim",
      rowType: PackClaim.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (PackClaim.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    pack_usage_stat: {
      tableName: "pack_usage_stat",
      rowType: PackUsageStat.getTypeScriptAlgebraicType(),
      primaryKey: "packId",
      primaryKeyInfo: {
        colName: "packId",
        colType: (PackUsageStat.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    raffle_entry: {
      tableName: "raffle_entry",
      rowType: RaffleEntry.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (RaffleEntry.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    referral: {
      tableName: "referral",
      rowType: Referral.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Referral.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    timed_pull: {
      tableName: "timed_pull",
      rowType: TimedPull.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (TimedPull.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    user: {
      tableName: "user",
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (User.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    vibe_balance: {
      tableName: "vibe_balance",
      rowType: VibeBalance.getTypeScriptAlgebraicType(),
      primaryKey: "wallet",
      primaryKeyInfo: {
        colName: "wallet",
        colType: (VibeBalance.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    xp_transaction: {
      tableName: "xp_transaction",
      rowType: XpTransaction.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (XpTransaction.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    award_xp: {
      reducerName: "award_xp",
      argsType: AwardXp.getTypeScriptAlgebraicType(),
    },
    capture_email: {
      reducerName: "capture_email",
      argsType: CaptureEmail.getTypeScriptAlgebraicType(),
    },
    check_daily_limit: {
      reducerName: "check_daily_limit",
      argsType: CheckDailyLimit.getTypeScriptAlgebraicType(),
    },
    complete_referral: {
      reducerName: "complete_referral",
      argsType: CompleteReferral.getTypeScriptAlgebraicType(),
    },
    create_referral: {
      reducerName: "create_referral",
      argsType: CreateReferral.getTypeScriptAlgebraicType(),
    },
    create_user: {
      reducerName: "create_user",
      argsType: CreateUser.getTypeScriptAlgebraicType(),
    },
    enter_raffle: {
      reducerName: "enter_raffle",
      argsType: EnterRaffle.getTypeScriptAlgebraicType(),
    },
    get_raffle_count: {
      reducerName: "get_raffle_count",
      argsType: GetRaffleCount.getTypeScriptAlgebraicType(),
    },
    get_raffle_entries: {
      reducerName: "get_raffle_entries",
      argsType: GetRaffleEntries.getTypeScriptAlgebraicType(),
    },
    record_free_pull: {
      reducerName: "record_free_pull",
      argsType: RecordFreePull.getTypeScriptAlgebraicType(),
    },
    record_pull: {
      reducerName: "record_pull",
      argsType: RecordPull.getTypeScriptAlgebraicType(),
    },
    save_journal_entry: {
      reducerName: "save_journal_entry",
      argsType: SaveJournalEntry.getTypeScriptAlgebraicType(),
    },
    select_weighted_winner: {
      reducerName: "select_weighted_winner",
      argsType: SelectWeightedWinner.getTypeScriptAlgebraicType(),
    },
    toggle_favorite: {
      reducerName: "toggle_favorite",
      argsType: ToggleFavorite.getTypeScriptAlgebraicType(),
    },
    unlock_achievement: {
      reducerName: "unlock_achievement",
      argsType: UnlockAchievement.getTypeScriptAlgebraicType(),
    },
    update_username: {
      reducerName: "update_username",
      argsType: UpdateUsername.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.5.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AwardXp", args: AwardXp }
| { name: "CaptureEmail", args: CaptureEmail }
| { name: "CheckDailyLimit", args: CheckDailyLimit }
| { name: "CompleteReferral", args: CompleteReferral }
| { name: "CreateReferral", args: CreateReferral }
| { name: "CreateUser", args: CreateUser }
| { name: "EnterRaffle", args: EnterRaffle }
| { name: "GetRaffleCount", args: GetRaffleCount }
| { name: "GetRaffleEntries", args: GetRaffleEntries }
| { name: "RecordFreePull", args: RecordFreePull }
| { name: "RecordPull", args: RecordPull }
| { name: "SaveJournalEntry", args: SaveJournalEntry }
| { name: "SelectWeightedWinner", args: SelectWeightedWinner }
| { name: "ToggleFavorite", args: ToggleFavorite }
| { name: "UnlockAchievement", args: UnlockAchievement }
| { name: "UpdateUsername", args: UpdateUsername }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  awardXp(wallet: string, amount: bigint, reason: string) {
    const __args = { wallet, amount, reason };
    let __writer = new __BinaryWriter(1024);
    AwardXp.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("award_xp", __argsBuffer, this.setCallReducerFlags.awardXpFlags);
  }

  onAwardXp(callback: (ctx: ReducerEventContext, wallet: string, amount: bigint, reason: string) => void) {
    this.connection.onReducer("award_xp", callback);
  }

  removeOnAwardXp(callback: (ctx: ReducerEventContext, wallet: string, amount: bigint, reason: string) => void) {
    this.connection.offReducer("award_xp", callback);
  }

  captureEmail(email: string, username: string, action: ActionType, wallet: string | undefined) {
    const __args = { email, username, action, wallet };
    let __writer = new __BinaryWriter(1024);
    CaptureEmail.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("capture_email", __argsBuffer, this.setCallReducerFlags.captureEmailFlags);
  }

  onCaptureEmail(callback: (ctx: ReducerEventContext, email: string, username: string, action: ActionType, wallet: string | undefined) => void) {
    this.connection.onReducer("capture_email", callback);
  }

  removeOnCaptureEmail(callback: (ctx: ReducerEventContext, email: string, username: string, action: ActionType, wallet: string | undefined) => void) {
    this.connection.offReducer("capture_email", callback);
  }

  checkDailyLimit(wallet: string, dateString: string) {
    const __args = { wallet, dateString };
    let __writer = new __BinaryWriter(1024);
    CheckDailyLimit.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("check_daily_limit", __argsBuffer, this.setCallReducerFlags.checkDailyLimitFlags);
  }

  onCheckDailyLimit(callback: (ctx: ReducerEventContext, wallet: string, dateString: string) => void) {
    this.connection.onReducer("check_daily_limit", callback);
  }

  removeOnCheckDailyLimit(callback: (ctx: ReducerEventContext, wallet: string, dateString: string) => void) {
    this.connection.offReducer("check_daily_limit", callback);
  }

  completeReferral(referredWallet: string) {
    const __args = { referredWallet };
    let __writer = new __BinaryWriter(1024);
    CompleteReferral.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("complete_referral", __argsBuffer, this.setCallReducerFlags.completeReferralFlags);
  }

  onCompleteReferral(callback: (ctx: ReducerEventContext, referredWallet: string) => void) {
    this.connection.onReducer("complete_referral", callback);
  }

  removeOnCompleteReferral(callback: (ctx: ReducerEventContext, referredWallet: string) => void) {
    this.connection.offReducer("complete_referral", callback);
  }

  createReferral(referrerWallet: string, referredWallet: string, referredUsername: string) {
    const __args = { referrerWallet, referredWallet, referredUsername };
    let __writer = new __BinaryWriter(1024);
    CreateReferral.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_referral", __argsBuffer, this.setCallReducerFlags.createReferralFlags);
  }

  onCreateReferral(callback: (ctx: ReducerEventContext, referrerWallet: string, referredWallet: string, referredUsername: string) => void) {
    this.connection.onReducer("create_referral", callback);
  }

  removeOnCreateReferral(callback: (ctx: ReducerEventContext, referrerWallet: string, referredWallet: string, referredUsername: string) => void) {
    this.connection.offReducer("create_referral", callback);
  }

  createUser(wallet: string, username: string) {
    const __args = { wallet, username };
    let __writer = new __BinaryWriter(1024);
    CreateUser.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_user", __argsBuffer, this.setCallReducerFlags.createUserFlags);
  }

  onCreateUser(callback: (ctx: ReducerEventContext, wallet: string, username: string) => void) {
    this.connection.onReducer("create_user", callback);
  }

  removeOnCreateUser(callback: (ctx: ReducerEventContext, wallet: string, username: string) => void) {
    this.connection.offReducer("create_user", callback);
  }

  enterRaffle(wallet: string, username: string, email: string, tokenBalance: string, usdValue: number) {
    const __args = { wallet, username, email, tokenBalance, usdValue };
    let __writer = new __BinaryWriter(1024);
    EnterRaffle.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("enter_raffle", __argsBuffer, this.setCallReducerFlags.enterRaffleFlags);
  }

  onEnterRaffle(callback: (ctx: ReducerEventContext, wallet: string, username: string, email: string, tokenBalance: string, usdValue: number) => void) {
    this.connection.onReducer("enter_raffle", callback);
  }

  removeOnEnterRaffle(callback: (ctx: ReducerEventContext, wallet: string, username: string, email: string, tokenBalance: string, usdValue: number) => void) {
    this.connection.offReducer("enter_raffle", callback);
  }

  getRaffleCount() {
    this.connection.callReducer("get_raffle_count", new Uint8Array(0), this.setCallReducerFlags.getRaffleCountFlags);
  }

  onGetRaffleCount(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_raffle_count", callback);
  }

  removeOnGetRaffleCount(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_raffle_count", callback);
  }

  getRaffleEntries() {
    this.connection.callReducer("get_raffle_entries", new Uint8Array(0), this.setCallReducerFlags.getRaffleEntriesFlags);
  }

  onGetRaffleEntries(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_raffle_entries", callback);
  }

  removeOnGetRaffleEntries(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_raffle_entries", callback);
  }

  recordFreePull(wallet: string) {
    const __args = { wallet };
    let __writer = new __BinaryWriter(1024);
    RecordFreePull.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("record_free_pull", __argsBuffer, this.setCallReducerFlags.recordFreePullFlags);
  }

  onRecordFreePull(callback: (ctx: ReducerEventContext, wallet: string) => void) {
    this.connection.onReducer("record_free_pull", callback);
  }

  removeOnRecordFreePull(callback: (ctx: ReducerEventContext, wallet: string) => void) {
    this.connection.offReducer("record_free_pull", callback);
  }

  recordPull(wallet: string, cardId: number, dateString: string, packId: string | undefined) {
    const __args = { wallet, cardId, dateString, packId };
    let __writer = new __BinaryWriter(1024);
    RecordPull.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("record_pull", __argsBuffer, this.setCallReducerFlags.recordPullFlags);
  }

  onRecordPull(callback: (ctx: ReducerEventContext, wallet: string, cardId: number, dateString: string, packId: string | undefined) => void) {
    this.connection.onReducer("record_pull", callback);
  }

  removeOnRecordPull(callback: (ctx: ReducerEventContext, wallet: string, cardId: number, dateString: string, packId: string | undefined) => void) {
    this.connection.offReducer("record_pull", callback);
  }

  saveJournalEntry(wallet: string, cardId: number, date: __Timestamp, prompt1: string, prompt2: string, prompt3: string, wordCount: number, completed: boolean) {
    const __args = { wallet, cardId, date, prompt1, prompt2, prompt3, wordCount, completed };
    let __writer = new __BinaryWriter(1024);
    SaveJournalEntry.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("save_journal_entry", __argsBuffer, this.setCallReducerFlags.saveJournalEntryFlags);
  }

  onSaveJournalEntry(callback: (ctx: ReducerEventContext, wallet: string, cardId: number, date: __Timestamp, prompt1: string, prompt2: string, prompt3: string, wordCount: number, completed: boolean) => void) {
    this.connection.onReducer("save_journal_entry", callback);
  }

  removeOnSaveJournalEntry(callback: (ctx: ReducerEventContext, wallet: string, cardId: number, date: __Timestamp, prompt1: string, prompt2: string, prompt3: string, wordCount: number, completed: boolean) => void) {
    this.connection.offReducer("save_journal_entry", callback);
  }

  selectWeightedWinner() {
    this.connection.callReducer("select_weighted_winner", new Uint8Array(0), this.setCallReducerFlags.selectWeightedWinnerFlags);
  }

  onSelectWeightedWinner(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("select_weighted_winner", callback);
  }

  removeOnSelectWeightedWinner(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("select_weighted_winner", callback);
  }

  toggleFavorite(wallet: string, cardId: number, note: string | undefined) {
    const __args = { wallet, cardId, note };
    let __writer = new __BinaryWriter(1024);
    ToggleFavorite.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("toggle_favorite", __argsBuffer, this.setCallReducerFlags.toggleFavoriteFlags);
  }

  onToggleFavorite(callback: (ctx: ReducerEventContext, wallet: string, cardId: number, note: string | undefined) => void) {
    this.connection.onReducer("toggle_favorite", callback);
  }

  removeOnToggleFavorite(callback: (ctx: ReducerEventContext, wallet: string, cardId: number, note: string | undefined) => void) {
    this.connection.offReducer("toggle_favorite", callback);
  }

  unlockAchievement(wallet: string, achievementId: string) {
    const __args = { wallet, achievementId };
    let __writer = new __BinaryWriter(1024);
    UnlockAchievement.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("unlock_achievement", __argsBuffer, this.setCallReducerFlags.unlockAchievementFlags);
  }

  onUnlockAchievement(callback: (ctx: ReducerEventContext, wallet: string, achievementId: string) => void) {
    this.connection.onReducer("unlock_achievement", callback);
  }

  removeOnUnlockAchievement(callback: (ctx: ReducerEventContext, wallet: string, achievementId: string) => void) {
    this.connection.offReducer("unlock_achievement", callback);
  }

  updateUsername(wallet: string, username: string) {
    const __args = { wallet, username };
    let __writer = new __BinaryWriter(1024);
    UpdateUsername.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_username", __argsBuffer, this.setCallReducerFlags.updateUsernameFlags);
  }

  onUpdateUsername(callback: (ctx: ReducerEventContext, wallet: string, username: string) => void) {
    this.connection.onReducer("update_username", callback);
  }

  removeOnUpdateUsername(callback: (ctx: ReducerEventContext, wallet: string, username: string) => void) {
    this.connection.offReducer("update_username", callback);
  }

}

export class SetReducerFlags {
  awardXpFlags: __CallReducerFlags = 'FullUpdate';
  awardXp(flags: __CallReducerFlags) {
    this.awardXpFlags = flags;
  }

  captureEmailFlags: __CallReducerFlags = 'FullUpdate';
  captureEmail(flags: __CallReducerFlags) {
    this.captureEmailFlags = flags;
  }

  checkDailyLimitFlags: __CallReducerFlags = 'FullUpdate';
  checkDailyLimit(flags: __CallReducerFlags) {
    this.checkDailyLimitFlags = flags;
  }

  completeReferralFlags: __CallReducerFlags = 'FullUpdate';
  completeReferral(flags: __CallReducerFlags) {
    this.completeReferralFlags = flags;
  }

  createReferralFlags: __CallReducerFlags = 'FullUpdate';
  createReferral(flags: __CallReducerFlags) {
    this.createReferralFlags = flags;
  }

  createUserFlags: __CallReducerFlags = 'FullUpdate';
  createUser(flags: __CallReducerFlags) {
    this.createUserFlags = flags;
  }

  enterRaffleFlags: __CallReducerFlags = 'FullUpdate';
  enterRaffle(flags: __CallReducerFlags) {
    this.enterRaffleFlags = flags;
  }

  getRaffleCountFlags: __CallReducerFlags = 'FullUpdate';
  getRaffleCount(flags: __CallReducerFlags) {
    this.getRaffleCountFlags = flags;
  }

  getRaffleEntriesFlags: __CallReducerFlags = 'FullUpdate';
  getRaffleEntries(flags: __CallReducerFlags) {
    this.getRaffleEntriesFlags = flags;
  }

  recordFreePullFlags: __CallReducerFlags = 'FullUpdate';
  recordFreePull(flags: __CallReducerFlags) {
    this.recordFreePullFlags = flags;
  }

  recordPullFlags: __CallReducerFlags = 'FullUpdate';
  recordPull(flags: __CallReducerFlags) {
    this.recordPullFlags = flags;
  }

  saveJournalEntryFlags: __CallReducerFlags = 'FullUpdate';
  saveJournalEntry(flags: __CallReducerFlags) {
    this.saveJournalEntryFlags = flags;
  }

  selectWeightedWinnerFlags: __CallReducerFlags = 'FullUpdate';
  selectWeightedWinner(flags: __CallReducerFlags) {
    this.selectWeightedWinnerFlags = flags;
  }

  toggleFavoriteFlags: __CallReducerFlags = 'FullUpdate';
  toggleFavorite(flags: __CallReducerFlags) {
    this.toggleFavoriteFlags = flags;
  }

  unlockAchievementFlags: __CallReducerFlags = 'FullUpdate';
  unlockAchievement(flags: __CallReducerFlags) {
    this.unlockAchievementFlags = flags;
  }

  updateUsernameFlags: __CallReducerFlags = 'FullUpdate';
  updateUsername(flags: __CallReducerFlags) {
    this.updateUsernameFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get achievement(): AchievementTableHandle {
    // clientCache is a private property
    return new AchievementTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Achievement>(REMOTE_MODULE.tables.achievement));
  }

  get activePack(): ActivePackTableHandle {
    // clientCache is a private property
    return new ActivePackTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ActivePack>(REMOTE_MODULE.tables.active_pack));
  }

  get cardPull(): CardPullTableHandle {
    // clientCache is a private property
    return new CardPullTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<CardPull>(REMOTE_MODULE.tables.card_pull));
  }

  get emailCapture(): EmailCaptureTableHandle {
    // clientCache is a private property
    return new EmailCaptureTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<EmailCapture>(REMOTE_MODULE.tables.email_capture));
  }

  get favorite(): FavoriteTableHandle {
    // clientCache is a private property
    return new FavoriteTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Favorite>(REMOTE_MODULE.tables.favorite));
  }

  get freePull(): FreePullTableHandle {
    // clientCache is a private property
    return new FreePullTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<FreePull>(REMOTE_MODULE.tables.free_pull));
  }

  get journalEntry(): JournalEntryTableHandle {
    // clientCache is a private property
    return new JournalEntryTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<JournalEntry>(REMOTE_MODULE.tables.journal_entry));
  }

  get journalStreak(): JournalStreakTableHandle {
    // clientCache is a private property
    return new JournalStreakTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<JournalStreak>(REMOTE_MODULE.tables.journal_streak));
  }

  get packClaim(): PackClaimTableHandle {
    // clientCache is a private property
    return new PackClaimTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PackClaim>(REMOTE_MODULE.tables.pack_claim));
  }

  get packUsageStat(): PackUsageStatTableHandle {
    // clientCache is a private property
    return new PackUsageStatTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PackUsageStat>(REMOTE_MODULE.tables.pack_usage_stat));
  }

  get raffleEntry(): RaffleEntryTableHandle {
    // clientCache is a private property
    return new RaffleEntryTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<RaffleEntry>(REMOTE_MODULE.tables.raffle_entry));
  }

  get referral(): ReferralTableHandle {
    // clientCache is a private property
    return new ReferralTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Referral>(REMOTE_MODULE.tables.referral));
  }

  get timedPull(): TimedPullTableHandle {
    // clientCache is a private property
    return new TimedPullTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<TimedPull>(REMOTE_MODULE.tables.timed_pull));
  }

  get user(): UserTableHandle {
    // clientCache is a private property
    return new UserTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }

  get vibeBalance(): VibeBalanceTableHandle {
    // clientCache is a private property
    return new VibeBalanceTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<VibeBalance>(REMOTE_MODULE.tables.vibe_balance));
  }

  get xpTransaction(): XpTransactionTableHandle {
    // clientCache is a private property
    return new XpTransactionTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<XpTransaction>(REMOTE_MODULE.tables.xp_transaction));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
